/**
 * The five pose prompts from the Saree Generation Playbook, verbatim.
 *
 * Lifted straight from the published artifact rather than retyped, so the text
 * the engine sends is character-for-character what was proven on real kalamkari.
 * These are used when a request asks for promptSource "playbook" — the engine's
 * own composed prompts are the default, and these are the control to test them
 * against.
 *
 * Do not edit by hand. They are a fixed reference point; if the wording should
 * change, it changes in the composed prompt, not here.
 */
export const PLAYBOOK_PROMPTS: Record<string, string> = {
  "front":
    "A professional fashion catalog photo of a woman in her mid-20s wearing a cotton saree as per the reference image. She stands facing the camera directly in a symmetrical, centered pose, with both hands clasped together at her waist. The saree pallu is pleated neatly and thrown up and over the left shoulder from front to back, forming a distinct peaked, pointed shape of fabric rising at the shoulder edge before going over and down her back. Only the front portion of the pallu near the collarbone and shoulder point is visible; the majority of the pallu length falls behind her shoulder and down her back, out of view from the front. The pleats must be clean, straight, and evenly spaced — like neatly pressed fabric folds, not bunched or crumpled. She has a direct, confident gaze and a neutral-to-soft expression. Full-length portrait, tightly framed so her figure fills most of the vertical frame from head to feet, shot straight-on at eye level with minimal headroom and minimal space around her. She is positioned in a sunlit traditional Indian courtyard, framed symmetrically by a single stone arch directly behind her head, with pillars on either side, background softly blurred. Styled with gold jhumka earrings, a gold choker-style necklace, and bangles. Warm, golden directional lighting.",
  "three-quarter":
    "Using the exact saree fabric and print shown in the reference image, generate a professional fashion catalog photo of a woman in her mid-20s wearing this saree exactly as shown, without altering, redesigning, or reinterpreting the fabric pattern, print, or colors in any way. The blouse has short sleeves that end above the elbow, well before the elbow joint, exposing the forearm. She has a direct, confident gaze and a neutral-to-soft expression. Full-length portrait, tightly framed so her figure fills most of the vertical frame from head to feet, shot straight-on at eye level with minimal headroom and minimal space around her. She is positioned in a sunlit traditional Indian courtyard, framed symmetrically by a single stone arch directly behind her head, with pillars on either side, background softly blurred. Styled with gold jhumka earrings, a gold choker-style necklace, and bangles. Warm, golden directional lighting. She stands at a slight three-quarter angle to the camera, shoulders and hips turned about 30 degrees away from straight-on, with her face turned back toward the camera. One hand rests lightly on her hip; the other arm hangs naturally at her side. The pallu is pleated neatly and draped over the left shoulder, falling forward along the front of her body so the full length of the pleats, pattern, and border are visible down to the hem. The pleats are clean, straight, and evenly spaced.",
  "back":
    "Using the exact saree fabric and print shown in the reference image, generate a professional fashion catalog photo of a woman in her mid-20s wearing this saree exactly as shown, without altering, redesigning, or reinterpreting the fabric pattern, print, or colors in any way. The blouse has short sleeves that end above the elbow, well before the elbow joint, exposing the forearm. She has a direct, confident gaze and a neutral-to-soft expression. Full-length portrait, tightly framed so her figure fills most of the vertical frame from head to feet, shot straight-on at eye level with minimal headroom and minimal space around her. She is positioned in a sunlit traditional Indian courtyard, framed symmetrically by a single stone arch directly behind her head, with pillars on either side, background softly blurred. Styled with gold jhumka earrings, a gold choker-style necklace, and bangles. Warm, golden directional lighting. She stands with her back to the camera, head turned gently to one side in profile, hair worn down over one shoulder so the blouse back and neckline are visible. The pallu is pleated neatly and draped over one shoulder from behind, with the pleats falling down her back and visible against the saree body. The lower drape, pleats at the waist, and hem are fully visible from behind. The pleats are clean, straight, and evenly spaced.",
  "waist-up":
    "Using the exact saree fabric and print shown in the reference image, generate a professional fashion catalog photo of a woman in her mid-20s wearing this saree exactly as shown, without altering, redesigning, or reinterpreting the fabric pattern, print, or colors in any way. The blouse has short sleeves that end above the elbow, well before the elbow joint, exposing the forearm. She has a direct, confident gaze and a neutral-to-soft expression. She is positioned in a sunlit traditional Indian courtyard, framed symmetrically by a single stone arch directly behind her head, with pillars on either side, background softly blurred. Styled with gold jhumka earrings, a gold choker-style necklace, and bangles. Warm, golden directional lighting. Tightly cropped from the waist up, facing the camera directly with a slight three-quarter turn of the shoulders. Both hands rest together just below the waist, at the bottom edge of the frame. The pallu is pleated neatly and draped over the left shoulder, with the pleats, border pattern, and pallu drape clearly visible in sharp detail across the chest and shoulder. The pleats are clean, straight, and evenly spaced. Framing shows head, shoulders, and torso down to the waist only.",
  "relaxed":
    "Using the exact saree fabric and print shown in the reference image, generate a professional fashion catalog photo of a woman in her mid-20s wearing this saree exactly as shown, without altering, redesigning, or reinterpreting the fabric pattern, print, or colors in any way. The blouse has short sleeves that end above the elbow, well before the elbow joint, exposing the forearm. Full-length portrait, tightly framed so her figure fills most of the vertical frame from head to feet, shot at eye level with minimal headroom and minimal space around her. She is positioned in a sunlit traditional Indian courtyard, framed by a stone arch behind her, with pillars on either side, background softly blurred. Styled with gold jhumka earrings, a gold choker-style necklace, and bangles. Warm, golden directional lighting. She stands in a relaxed, natural three-quarter pose, with her weight shifted onto one leg and her hip gently angled toward the camera, the way a person naturally stands when resting on one side. One hand rests lightly on her hip; the other arm hangs naturally at her side. Her head and neck follow the natural line of her shoulders, with a soft, easy turn of the face toward the camera — no strain or awkward angle between head and body. The pallu is pleated neatly and draped over the shoulder, falling forward along the front of her body so the full length of the pleats, pattern, and border are visible down to the hem. The pleats are clean, straight, and evenly spaced. Direct, confident gaze, neutral-to-soft expression.",
};
