/**
 * Every word on the studio screens, in one place.
 *
 * Written to read like the competitor's app, because that is what this is
 * judged against, with Tantu's name where theirs was.
 */
export const T = {
  header: { back: "Back", newGarment: "Start new garment", appLabel: "Try-On" },
  splash: { name: "Tantu", tagline: "AI Studio for Fashion Brands" },
  status: { trial: "Trial" },
  entry: {
    title: "Your AI Fashion Shoot Studio",
    copy: "Transform garment photos into premium model catalog shoots in seconds.",
    start: "Start",
    upload: "Upload Garment",
    slkLink: "Have an SLK product code?",
    slkPlaceholder: "300010",
    slkFind: "Find",
  },
  upload: {
    title: "What are you uploading?",
    copy: "Pick the garment type first. It decides which photos we ask for.",
    typeLabel: "Garment type",
    typeHelp: "Saree is live. The other types are coming soon.",
    calloutPrefix: "✨ Hanging the saree on the rod?",
    seeTips: "See Tips",
    calloutSuffix: "for the shots.",
    dropzone: "Continue to photos",
    dropzoneCopy: "Next: the list of photos to take, one tile each.",
    change: "Change image",
    tooLargeTitle: "Image is too large",
    tooLarge: "Please upload a smaller-sized garment image so we can process it properly.",
    tooLargeButton: "Upload another image",
    tipsTitle: "How to shoot a saree on the rod",
    slideGood: "Do this",
    slideCaution: "Avoid",
    slides: [
      { good: true, photo: "/shots/saree/whole.jpg", orientation: null, title: "Hang it once, like this", copy: "Drape the saree over the rod so the line where the pallu meets the body is at your chest. Plain cloth behind. Then do not touch the saree again — only the phone moves." },
      { good: true, photo: "/shots/saree/frame_body.jpg", orientation: "upright", title: "Body", copy: "Phone upright, a step and a half back, eye level. Both borders inside the frame, edge to edge, two or three motif repeats. Stop above the join." },
      { good: true, photo: "/shots/saree/frame_pallu.jpg", orientation: "upright", title: "Pallu", copy: "Phone upright, same spot, waist height. A thin band of body at the top, both borders inside, the end edge of the pallu at the bottom." },
      { good: true, photo: "/shots/saree/frame_border.jpg", orientation: "upright", title: "Border, only if it has its own design", copy: "Phone upright, at the side, half a metre away. The border in the middle third of the frame, fabric edge on one side, a hand of body on the other." },
      { good: true, photo: "/shots/saree/blouse.jpg", orientation: "sideways", title: "Blouse piece", copy: "Turn the phone sideways. Phone at knee height, or crouch. The plain end at the bottom fills the frame." },
      { good: true, photo: "/shots/saree/body_motif.jpg", orientation: "upright", title: "Body motif", copy: "Hold the phone upright. Step in close so one figure or one motif fills the frame, sharp. For a small repeat, get three or four in." },
      { good: true, photo: "/shots/saree/pallu_motif.jpg", orientation: "sideways", title: "Pallu motif", copy: "Turn the phone sideways. Step in close at waist height so one band of the brocade fills the frame." },
      { good: false, photo: "/shots/saree/avoid_blur.jpg", orientation: null, title: "Shaken", copy: "Hold still and tap once. A soft photo prints soft; the check will ask for a retake." },
      { good: false, photo: "/shots/saree/avoid_clutter.jpg", orientation: null, title: "Shelves, hands, clips in frame", copy: "Only fabric in the frame. Other sarees and the shop behind get copied into the result." },
      { good: false, photo: "/shots/saree/avoid_angled.jpg", orientation: null, title: "Tilted or from below", copy: "Keep the phone square to the fabric for every close shot. An angle is fine only for the whole-saree photo." },
    ],
    tip: "Hang once. Body at eye level, pallu at waist, blouse at the knee. Upright for tall parts, sideways for wide ones.",
  },
  shots: {
    title: (type: string) => `${type} photos`,
    copy: "Hang it once. Only the phone moves.",
    required: "Required",
    optional: "Optional",
    camera: "Camera",
    upload: "Upload",
    retake: "Retake",
    clear: "Remove",
    how: "How",
    howTitle: "How to shoot the",
    frameCaption: "On the rod, phone straight ahead. Frame it like this.",
    upright: "Upright",
    sideways: "Sideways",
    good: "Looks good",
    requiredNote: "This photo is required. Continue stays off until it is in and clear.",
    optionalNote: "Optional. Skip it if the saree does not have it; it helps the result when it does.",
    progress: (have: number, need: number) => `${have} of ${need} required`,
    retakeCount: (n: number) => (n === 1 ? "1 needs a retake" : `${n} need a retake`),
    continueMissing: (labels: string[]) => `Continue · add ${labels.join(" and ")} first`,
    continueRetake: (labels: string[]) => `Continue · retake ${labels.join(" and ")} first`,
    support: "Camera opens the phone camera. Upload picks a photo already on the phone.",
    moreLabel: "Optional. Add the ones this saree has:",
    hide: "Hide",
    uploading: "Checking the photo…",
  },
  confirm: {
    title: "Confirm your photos",
    copy: (type: string, n: number) => `${n === 1 ? "1 photo" : `${n} photos`} of a ${type.toLowerCase()}. Tap a photo to change it. The type you chose is below; change it if it is wrong, it affects the result.`,
    addMore: "Add more",
    analyzing: "Analyzing your garment. This may take a few seconds.",
    analyzingMobile: "Keep this screen open and your phone unlocked.",
    preparing: "Preparing garment details. This may take a few seconds.",
    continue: "Looks correct, continue?",
    uploadBetter: "Upload a better photo",
    seeTips: "See Tips",
    error: "We could not analyze this image. Please go back and try another one.",
    groups: { women: "Women", men: "Men", kids: "Kids", other: "Other" },
    soon: "Soon",
  },
  details: {
    title: "Garment details",
    copy: "Review the main garment details. Change them if needed.",
    borders: { label: "Borders", help: "Does this saree have borders along the long edges? Select yes if such borders are visible." },
    bordersIdentical: { label: "Both Borders Identical?", help: "Some sarees have one border, usually at the bottom hem, that is bigger than the top border. Select NO if that is the case here." },
    blouseSame: { label: "Blouse piece same as body?", help: "A self blouse is cut from the saree body fabric. Select NO if the blouse piece is a different fabric or colour." },
    words: { label: "The saree in words", help: "What the AI read from your photo. Correct any colour that is wrong; the render follows these words.", edit: "Edit", done: "Done", readAgain: "Read from photo" },
  },
  flats: {
    title: "Additional photos",
    copy: "Add these if you have them, for accuracy and better styling. Don’t worry if you don’t.",
    optional: "Optional",
    upload: "Upload",
    change: "Change image",
    clear: "Clear",
    empty: "No image",
    items: {
      blouse: { label: "Blouse piece image", help: "Upload a blouse piece image if available. If you skip it, the model wears a plain blouse in the colour of the saree's border." },
      pallu: { label: "Pallu close-up", help: "A closer photo of the pallu end keeps its motif exact in every pose." },
      border: { label: "Border close-up", help: "A straight run of the border, edge parallel to the frame, keeps its width and design true." },
    },
  },
  model: {
    title: "Choose model",
    copy: "Select a model for your fashion shoot.",
    women: "Women",
    men: "Men",
    kids: "Kids",
    required: "Please select a model to continue.",
    fixed: "Hair, jewellery and light are the same for every image so your catalogue looks like one shoot.",
  },
  background: {
    title: "Choose background",
    copy: "Pick a background style for your final image.",
    best: "Best for this flow",
    selected: "Selected",
  },
  output: {
    title: "Choose output",
    copy: "Choose image size and shape.",
    resolution: "Resolution",
    aspect: "Aspect ratio",
    recommended: "Recommended",
    help1k: "Catalog",
    help2k: "Zoom detail",
    portrait: "Portrait",
    soon: "Soon",
    trialHint: "Choose the output size and aspect ratio for your first result.",
    exhausted: "Your current plan balance is over. Purchase a plan to continue.",
  },
  generate: {
    title: "Your image is ready",
    copy: "Download the result, create a catalog, or start a new garment.",
    action: "Generate",
    processing: "Generating your image. This can take up to a minute.",
    processingMobile: "Keep this screen open and your phone unlocked.",
    download: "Download",
    regenerateTitle: "Regenerate this primary image?",
    regenerateMessage: "This will create a new image and use your balance. Your old image will remain in Gallery.",
    poses: "Create More Poses",
    rate: "Rate image",
    up: "Good image",
    neutral: "Okay image",
    down: "Poor image",
    restart: "Start a New Garment",
    restartTitle: "Start a new garment?",
    restartMessage: "This will discard your current progress. Are you sure you want to continue?",
    restartButton: "Start New Garment",
    failedTitle: "Generation failed",
    failed: "We could not generate the image right now. Please try again.",
    blockedTitle: "Generation blocked",
    blocked: "This image could not be generated because the safety filter was triggered. Please review the garment image and try again.",
    notCharged: "Nothing was charged for this.",
    tryAgain: "Try again",
  },
  poses: {
    title: "Choose poses",
    copy: "Select one or more poses for this garment.",
    generate: "Generate",
    generateNew: "Generate New Poses",
    required: "Choose at least one pose to continue.",
    empty: "No additional poses are available for this garment.",
    limitTitle: "A few more poses need a recharge",
    limit: (n: number) => `You can select up to ${n} poses at this resolution with your current balance. Choose fewer poses or recharge to continue.`,
    recharge: "Recharge",
    processing: "Generating your image(s). This can take up to a minute.",
    groups: { front: "Front", side: "Side", back: "Back", garment: "Garment", other: "More Poses" },
  },
  gallery: {
    title: "Pose results",
    copy: "Review the generated poses and download the ones you want.",
    download: "Download",
    downloadAll: "Download All",
    more: "Create More Poses",
    regenerateTitle: "Regenerate this pose image?",
    regenerateMessage: "This will create a new image and use your balance. Your old image will remain in Gallery.",
    previous: "Previous",
    next: "Next",
  },
  myImages: {
    title: "Gallery",
    copy: "Your generated catalog photos.",
    empty: "Your generated images will appear here.",
    viewFull: "View Full Image",
  },
  profile: {
    title: "Account",
    copy: "Check your sign-in, plan status, and remaining balance here.",
    number: "Signed in as",
    plan: "Current plan",
    value: "Plan value",
    remaining: "Remaining",
    possible: "Images possible at each resolution based on your remaining balance",
    links: "Useful links",
    logout: "Logout",
    trial: "Trial",
    gallery: "Gallery",
    spend: "Platform: model, prices, shops, spend",
    shop: "Shop: people and usage",
  },
  pricing: {
    title: "Plans",
    copy: "Prepaid packs. Credits don’t expire, failed renders don’t cost you, commercial use included.",
    ask: "Ask for this pack",
    note: "Online payment is coming. Until then a pack is set up with you by hand.",
  },
  footer: { balance: (v: string) => `${v} left`, recharge: "Recharge", buy: "Buy" },
  common: { continue: "Continue", cancel: "Cancel", ok: "OK", yes: "Yes", no: "No", close: "Close", wait: "Please wait...", loading: "Loading images..." },
} as const;
