/**
 * Every word on the studio screens, in one place.
 *
 * Written to read like the competitor's app, because that is what this is
 * judged against, with Tantu's name where theirs was.
 */
export const T = {
  header: { back: "Back", newGarment: "Start new garment", appLabel: "Try-On" },
  splash: { name: "Tantu", tagline: "AI Studio for Fashion Brands" },
  status: { trial: "Trial" },
  entry: {
    title: "Your AI Fashion Shoot Studio",
    copy: "Transform garment photos into premium model catalog shoots in seconds.",
    start: "Start",
    upload: "Upload Garment",
    slkLink: "Have an SLK product code?",
    slkPlaceholder: "300010",
    slkFind: "Find",
  },
  upload: {
    title: "Upload garment image",
    copy: "Use a good garment image for best results.",
    calloutPrefix: "✨ Uploading a saree?",
    seeTips: "See Tips",
    calloutSuffix: "to get better results.",
    dropzone: "Upload Garment Image",
    dropzoneCopy: "Tap to open your phone or system file picker.",
    change: "Change image",
    tooLargeTitle: "Image is too large",
    tooLarge: "Please upload a smaller-sized garment image so we can process it properly.",
    tooLargeButton: "Upload another image",
    tipsTitle: "What kind of saree photo works best for Tantu?",
    overlayBody: "Saree Body",
    overlayPallu: "Pallu",
    slideGood: "Best results",
    slideCaution: "Can still work",
    slides: [
      { good: true, title: "Use the 50-50 saree view", copy: "For best results, keep the lower half of the photo focused on the pallu panel and the upper half on the saree body. Make sure both long borders are clearly visible." },
      { good: true, title: "Let the saree body show properly too", copy: "If the saree has the same repeating pattern, showing only a part of it above the full pallu in the photo is enough. You do not need to photograph the entire saree." },
      { good: true, title: "Make the borders easy to notice", copy: "Do not leave too much space around the saree, especially if the borders are unique. This helps us read them better." },
      { good: false, title: "This may still generate, but it is less reliable", copy: "AI generates what it sees and imagines what it cannot. This photo can work, but accuracy is not guaranteed." },
      { good: false, title: "The AI may need to guess more here", copy: "A mannequin-draped photo can work, but it may not show all the saree details needed for different poses." },
    ],
    tip: "For sarees, a vertical flat usually works best. Try to show the full pallu and a bit of the saree body above it, with very little empty space on the sides.",
  },
  confirm: {
    title: "Confirm garment type",
    copy: "We auto-detected the garment type below. Please change it if it’s incorrect, because this affects your final result.",
    analyzing: "Analyzing your garment. This may take a few seconds.",
    analyzingMobile: "Keep this screen open and your phone unlocked.",
    preparing: "Preparing garment details. This may take a few seconds.",
    continue: "Looks correct, continue?",
    uploadBetter: "Upload a better photo",
    seeTips: "See Tips",
    error: "We could not analyze this image. Please go back and try another one.",
    groups: { women: "Women", men: "Men", kids: "Kids", other: "Other" },
    soon: "Soon",
  },
  details: {
    title: "Garment details",
    copy: "Review the main garment details. Change them if needed.",
    borders: { label: "Borders", help: "Does this saree have borders along the long edges (किनारा / काठ)? Select yes if such borders are visible." },
    bordersIdentical: { label: "Both Borders Identical?", help: "Some sarees have one border, usually at the bottom hem, that is bigger than the top border. Select NO if that is the case here." },
    blouseSame: { label: "Blouse piece same as body?", help: "A self blouse is cut from the saree body fabric. Select NO if the blouse piece is a different fabric or colour." },
    words: { label: "The saree in words", help: "What the AI read from your photo. Correct any colour that is wrong; the render follows these words.", edit: "Edit", done: "Done", readAgain: "Read from photo" },
  },
  flats: {
    title: "Additional flats",
    copy: "Upload these flats for accuracy and better styling if you have them. Don’t worry if you don’t.",
    optional: "Optional",
    upload: "Upload",
    change: "Change image",
    clear: "Clear",
    empty: "No image",
    items: {
      blouse: { label: "Blouse piece image", help: "Upload a blouse piece image if available. If you skip it, we will create a matching blouse for you." },
      pallu: { label: "Pallu close-up", help: "A closer photo of the pallu end keeps its motif exact in every pose." },
      border: { label: "Border close-up", help: "A straight run of the border, edge parallel to the frame, keeps its width and design true." },
    },
  },
  model: {
    title: "Choose model",
    copy: "Select a model for your fashion shoot.",
    women: "Women",
    men: "Men",
    kids: "Kids",
    required: "Please select a model to continue.",
    fixed: "Hair, jewellery and light are the same for every image so your catalogue looks like one shoot.",
  },
  background: {
    title: "Choose background",
    copy: "Pick a background style for your final image.",
    best: "Best for this flow",
    selected: "Selected",
  },
  output: {
    title: "Choose output",
    copy: "Choose image size and shape.",
    resolution: "Resolution",
    aspect: "Aspect ratio",
    recommended: "Recommended",
    help1k: "Catalog",
    help2k: "Zoom detail",
    portrait: "Portrait",
    soon: "Soon",
    trialHint: "Choose the output size and aspect ratio for your first result.",
    exhausted: "Your current plan balance is over. Purchase a plan to continue.",
  },
  generate: {
    title: "Your image is ready",
    copy: "Download the result, create a catalog, or start a new garment.",
    action: "Generate",
    processing: "Generating your image. This can take up to a minute.",
    processingMobile: "Keep this screen open and your phone unlocked.",
    download: "Download",
    regenerateTitle: "Regenerate this primary image?",
    regenerateMessage: "This will create a new image and use your balance. Your old image will remain in Gallery.",
    poses: "Create More Poses",
    rate: "Rate image",
    up: "Good image",
    neutral: "Okay image",
    down: "Poor image",
    restart: "Start a New Garment",
    restartTitle: "Start a new garment?",
    restartMessage: "This will discard your current progress. Are you sure you want to continue?",
    restartButton: "Start New Garment",
    failedTitle: "Generation failed",
    failed: "We could not generate the image right now. Please try again.",
    blockedTitle: "Generation blocked",
    blocked: "This image could not be generated because the safety filter was triggered. Please review the garment image and try again.",
    notCharged: "Nothing was charged for this.",
    tryAgain: "Try again",
  },
  poses: {
    title: "Choose poses",
    copy: "Select one or more poses for this garment.",
    generate: "Generate",
    generateNew: "Generate New Poses",
    required: "Choose at least one pose to continue.",
    empty: "No additional poses are available for this garment.",
    limitTitle: "A few more poses need a recharge",
    limit: (n: number) => `You can select up to ${n} poses at this resolution with your current balance. Choose fewer poses or recharge to continue.`,
    recharge: "Recharge",
    processing: "Generating your image(s). This can take up to a minute.",
    groups: { front: "Front", side: "Side", back: "Back", garment: "Garment", other: "More Poses" },
  },
  gallery: {
    title: "Pose results",
    copy: "Review the generated poses and download the ones you want.",
    download: "Download",
    downloadAll: "Download All",
    more: "Create More Poses",
    regenerateTitle: "Regenerate this pose image?",
    regenerateMessage: "This will create a new image and use your balance. Your old image will remain in Gallery.",
    previous: "Previous",
    next: "Next",
  },
  myImages: {
    title: "Gallery",
    copy: "Your generated catalog photos.",
    empty: "Your generated images will appear here.",
    viewFull: "View Full Image",
  },
  profile: {
    title: "Account",
    copy: "Check your sign-in, plan status, and remaining balance here.",
    number: "Signed in as",
    plan: "Current plan",
    value: "Plan value",
    remaining: "Remaining",
    possible: "Images possible at each resolution based on your remaining balance",
    links: "Useful links",
    logout: "Logout",
    trial: "Trial",
    gallery: "Gallery",
    spend: "Spend and caps (admin)",
  },
  pricing: {
    title: "Plans",
    copy: "Prepaid packs. Credits don’t expire, failed renders don’t cost you, commercial use included.",
    ask: "Ask for this pack",
    note: "Online payment is coming. Until then a pack is set up with you by hand.",
  },
  footer: { balance: (v: string) => `${v} left`, recharge: "Recharge", buy: "Buy" },
  common: { continue: "Continue", cancel: "Cancel", ok: "OK", yes: "Yes", no: "No", close: "Close", wait: "Please wait...", loading: "Loading images..." },
} as const;
